version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "5001:8080"

  test:
    container_name: "test"
    build:
      context: .
      dockerfile: ./test/Dockerfile
    ports:
      - "5002:8080"

  authentication:
    container_name: "authentication"
    build:
      context: .
      dockerfile: ./authentication/Dockerfile
    ports:
      - "5003:8080"

  totp:
    container_name: "totp"
    build:
      context: .
      dockerfile: ./totp/Dockerfile
    ports:
      - "5004:8080"

  #blog:
  #  container_name: "blog"
  #  build:
  #    context: .
  #    dockerfile: ./blog/Dockerfile
  #  ports:
  #    - "5005:8080"
