version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    container_name: "api"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:8080"

  test:
    container_name: "test"
    build:
      context: ./test
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
