import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { CardActionArea } from "@mui/material";
//import dynamic from 'next/dynamic';
import ResponsiveAppBar from "../resource/components/global/headerBar";

//const header = dynamic(() => import('/pages/headerBar.js'));
//<header />

export default function Home() {
  return (
    <>
      <div>
        <ResponsiveAppBar />
      </div>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to the forum/blog</h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <Card sx={{ maxWidth: 345 }}>
              <CardActionArea href="/">
                <CardMedia
                  component="img"
                  height="140"
                  image=".\images\6e9.jpg"
                  alt="image not found"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    Wheels
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Wheeels are everywhere and they are really cool
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>

            <Card sx={{ maxWidth: 345 }}>
              <CardActionArea>
                <CardMedia
                  component="img"
                  height="140"
                  image=".\images\6e9.jpg"
                  alt="image not found"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    Wheels
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Wheeels are everywhere and they are really cool
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>

            <Card sx={{ maxWidth: 345 }}>
              <CardActionArea>
                <CardMedia
                  component="img"
                  height="140"
                  image=".\images\6e9.jpg"
                  alt="image not found"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    Wheels
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Wheeels are everywhere and they are really cool
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>

            <Card sx={{ maxWidth: 345 }}>
              <CardActionArea>
                <CardMedia
                  component="img"
                  height="140"
                  image=".\images\6e9.jpg"
                  alt="image not found"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    Wheels
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Wheeels are everywhere and they are really cool
                  </Typography>
                </CardContent>
              </CardActionArea>
            </Card>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
